services:
  cyber-punk-backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - cyber-punk-db
    environment:
      # mongo related credentials
      MONGO_USERNAME: cyberpunk
      MONGO_PASSWORD: password
      MONGO_DB_URI: mongodb://cyber-punk-db:27017/cyberpunk-db

      # token secrets
      JWT_SECRET: your_secret_key1
      REFRESH_TOKEN_SECRET: your_secret_key2

  cyber-punk-db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cyberpunkroot
      MONGO_USERNAME: cyberpunk
      MONGO_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./docker-compose-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
