version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: cyberpunk
      MONGO_PASSWORD: password
      MONGO_DB_URI: mongodb://mongo:27017/cyberpunk-db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cyberpunkroot
      MONGO_USERNAME: cyberpunk
      MONGO_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./docker-compose-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"

volumes:
  mongo_data:
